language: ruby
cache: bundler
install:
- bundle install
- npm install
script:
- "./build.sh"
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: _site
  fqdn: newhaven.io
  target-branch: gh-pages
  github-token: $DEPLOY_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
